version: "3.9"

services:
  redis:
    image: redis:7
    container_name: shortener_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  server:
    build:
      context: .
    container_name: shortener_server
    command: sh -c "./main"
    ports:
      - 80:80
    restart: always
    depends_on:
      - redis

volumes:
 redis_data: