version: "3.9"

services:
  redis:
    image: redis:7
    container_name: shortener_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - mynetwork
    networks:
      mynetwork:
        ipv4_address: 212.109.218.42

  server:
    build:
      context: .
    container_name: shortener_server
    command: sh -c "./main"
    ports:
      - 80:80
    restart: always
    depends_on:
      - redis
    networks:
      - mynetwork
    networks:
      mynetwork:
        ipv4_address: 212.109.218.42

volumes:
  redis_data:

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 212.109.218.0/24